version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 435588716893.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=435588716893.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/java-fargate
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - mvn --version
      - mvn package
      - echo Building the Docker image...
      - echo image name $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t java-fargate .
      - echo Tagging Docker image...
      - docker tag java-fargate:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - echo repository uri $REPOSITORY_URI
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: 
      - imagedefinitions.json
      - target/spring-boot-hello-world-example-0.0.1-SNAPSHOT.jar
